# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true
markdown: redcarpet
redcarpet:
    extensions: [with_toc_data]

# Setup
title:               Co-op Info
tagline:             'Co-op Resources in Cleveland'
description:         'A set of co-op resources made by Rikki.'
url:                 http://lanyon.getpoole.com
baseurl:             'coop-info'
paginate:            5

# About/contact
author:
  name:              Mark Otto
  url:               https://twitter.com/mdo
  email:             markdotto@gmail.com

# Custom vars
version:             1.0.0
